### ISSUE TITLE
error on ubuntu18.04

### ISSUE THREAD

**Issue by DHrobotman** [VIS4ROB-lab/multirotors_landing#2]
Hello, I attempted to rebuild the environment on ubuntu18.04 and encountered an incompatibility issue with the pybind11 version. Therefore, I replaced the pybind11 version with v2.9.0 and compiled successfully. However, when running the training code, the following error occurred:

```
(Landing) lyh@lyh-Predator-PO9-920 :~/multi robots_ Landing/multi robots_ Landing_ Rl $Python scripts/quadrotor_ Landing.py

Traceback (most recent call last):

File "scripts/quadrotor_landing. py", line 21, in<module>

From multirobots_ Landing_ Rl. envs import vec_ Env_ Landing as wrapper

File "/home/lyh/multirotors_landing/multirotors_landing_rl/multirotors_landing_rl/envs/vec_env_landing. py", line 11, in<module>

From multirobots_ Landing_ Rl. common. common_ Defs import\

File "/home/lyh/multirotors_landing/multirotors_landing_rl/multirotors_landing_rl/common/common_defs. py", line 32, in<module>

From mlgy import DoneReason

ImportError: dynamic module does not define module export function (PyInit_mlgym)
```

**Comment by lucaBartolomei** [comment]
Hello,

Unfortunately Ubuntu 18.04 is not supported from our side, as we don't even have a computer ready where to test build/running commands.

Since the error message you got is caused by some issue originated from pybind, I'd suggest to have a look at [this file](https://github.com/VIS4ROB-lab/multirotors_landing/blob/main/multirotors_landing_lib/src/wrapper/pybind_wrapper.cpp), and try to change it according the pybind version you are using (probably `enum` are not supported in older pybind versions, so you may need to change/remove them).

I hope this helps.
